# Official docker image.
stages: 
 - "maven-build"
 - "maven-deploy"
before_script:
  - "export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')"
maven-build:
  image: maven:3-jdk-8
  stage: maven-build
  script: " mvn clean package -Dmaven.test.skip=true"
  tags:
   - docker
  only:
   - laster
maven-deploy:
  image: maven:3-jdk-8
  stage: maven-deploy
  script: " mvn clean package deploy -Dmaven.test.skip=true -DdockerImageTags=${IMAGE_TAG}"
  tags:
   - docker
  only:
   - beta
   - release
   - tags